name: Unit test

on:  
  pull_request:
    branches:
    - master
    paths:
    - 'data_classes.py'
    - 'data_classes_test.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Unit test for data_classes
      run: |
        cd ..
        python -m thousandaire.data_classes_test
